version: "3"
services:
  react-app:
    build:
      dockerfile : Dockerfile
      context : ./frontend
    ports:
      - "3000:3000"
    
    networks:
      - mern-app
  node-app:
    build:
       dockerfile : Dockerfile
       context : ./backend
    ports:
      - "4000:4000"
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  nginx:
    restart: always
    depends_on:
      - react-app
      - node-app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
